name: Spring
main: com.neptune.spring.SpringPlugin
api-version: 1.21
version: 1.0
softdepend:
- WorldGuard
- PlaceholderAPI
- LuckPerms
commands:
  spring:
    description: "Spring Bounce Pad Plugin commands"
    usage: "/spring help"
